apiVersion: apps/v1
kind: Deployment
metadata:
  name: appadminator
  labels:
    app: appadminator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appadminator
  template:
    metadata:
      labels:
        app: appadminator
    spec:
      containers:
      - name: appadminator
        image: appadminator5009:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5009

---
apiVersion: v1
kind: Service
metadata:
  name: svc-appadminator
spec:
  type: NodePort
  selector:
    app: appadminator
  ports:
  - port: 5009
    targetPort: 5009

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskvolt
  labels:
    app: flaskvolt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskvolt
  template:
    metadata:
      labels:
        app: flaskvolt
    spec:
      containers:
      - name: flaskvolt
        image: flaskvolt:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5005

---
apiVersion: v1
kind: Service
metadata:
  name: svc-flaskvolt
spec:
  type: NodePort
  selector:
    app: flaskvolt
  ports:
  - port: 5005
    targetPort: 5005

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flasklight
  labels:
    app: flasklight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flasklight
  template:
    metadata:
      labels:
        app: flasklight
    spec:
      containers:
      - name: flasklight
        image: flasklight:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5005

---

apiVersion: v1
kind: Service
metadata:
  name: svc-flasklight
spec:
  type: NodePort
  selector:
    app: flasklight
  ports:
  - port: 5005
    targetPort: 5005

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskmaterial
  labels:
    app: flaskmaterial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskmaterial
  template:
    metadata:
      labels:
        app: flaskmaterial
    spec:
      containers:
      - name: flaskmaterial
        image: flaskmaterial:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5005

---

apiVersion: v1
kind: Service
metadata:
  name: svc-flaskmaterial
spec:
  type: NodePort
  selector:
    app: flaskmaterial
  ports:
  - port: 5005
    targetPort: 5005

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flasksoftui
  labels:
    app: flasksoftui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flasksoftui
  template:
    metadata:
      labels:
        app: flasksoftui
    spec:
      containers:
      - name: flasksoftui
        image: flasksoftui:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5005

---

apiVersion: v1
kind: Service
metadata:
  name: svc-flasksoftui
spec:
  type: NodePort
  selector:
    app: flasksoftui
  ports:
  - port: 5005
    targetPort: 5005